/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_tpv;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author borras
 */
public class Vista_tpv extends javax.swing.JFrame {

    /**
     * Creates new form Vista_tpv
     */
    public Vista_tpv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostraDades = new javax.swing.JTable();
        jButton_afegir = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_modificar = new javax.swing.JButton();
        jButtonBuscarProductes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDadaBuscar = new javax.swing.JTextField();
        jComboBoxBuscarPer = new javax.swing.JComboBox<>();
        jComboBoxOrdenarPer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonInfoBuscarPer = new javax.swing.JButton();
        jButtonAfegirCategoria = new javax.swing.JButton();
        jButtonEliminarCategoria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelSeccio9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanelSeccio4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanelSeccio2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelSeccio7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelSeccio5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelSeccio6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanelSeccio1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelSeccio8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanelSeccio3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanelSeccio10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelSeccio13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelSeccio12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelSeccio11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSliderStock = new javax.swing.JSlider();
        jTextFieldSliderValue = new javax.swing.JTextField();
        jButtonMostraStock = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabelSliderMin = new javax.swing.JLabel();
        jLabelSliderMax = new javax.swing.JLabel();
        jTextFieldAfegirCategoria = new javax.swing.JTextField();
        jComboBoxEliminarCategoria = new javax.swing.JComboBox<>();
        jButtonFiltaCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 669));

        jTableMostraDades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMostraDades);

        jButton_afegir.setText("Afegir Producte");

        jButton_eliminar.setText("Eliminar Producte");

        jButton_modificar.setText("Modificar Producte");

        jButtonBuscarProductes.setText("Mostrar Productes");

        jLabel1.setText("Dada a buscar:");

        jTextFieldDadaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDadaBuscarActionPerformed(evt);
            }
        });

        jComboBoxBuscarPer.setSelectedItem(jComboBoxBuscarPer);

        jLabel2.setText("Buscar per:");

        jLabel3.setText("Ordenar per:");

        jLabel4.setText("Buscar productes:");

        jButtonInfoBuscarPer.setText("?");
        jButtonInfoBuscarPer.setMargin(new java.awt.Insets(2, 5, 2, 5));

        jButtonAfegirCategoria.setText("Afegir Categoria");

        jButtonEliminarCategoria.setText("Eliminar Categoria");
        jButtonEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCategoriaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanelSeccio9.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio9.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel13.setText("9");

        javax.swing.GroupLayout jPanelSeccio9Layout = new javax.swing.GroupLayout(jPanelSeccio9);
        jPanelSeccio9.setLayout(jPanelSeccio9Layout);
        jPanelSeccio9Layout.setHorizontalGroup(
            jPanelSeccio9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelSeccio9Layout.setVerticalGroup(
            jPanelSeccio9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio4.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel8.setText("4");

        javax.swing.GroupLayout jPanelSeccio4Layout = new javax.swing.GroupLayout(jPanelSeccio4);
        jPanelSeccio4.setLayout(jPanelSeccio4Layout);
        jPanelSeccio4Layout.setHorizontalGroup(
            jPanelSeccio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelSeccio4Layout.setVerticalGroup(
            jPanelSeccio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio2.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel6.setText("2");

        javax.swing.GroupLayout jPanelSeccio2Layout = new javax.swing.GroupLayout(jPanelSeccio2);
        jPanelSeccio2.setLayout(jPanelSeccio2Layout);
        jPanelSeccio2Layout.setHorizontalGroup(
            jPanelSeccio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelSeccio2Layout.setVerticalGroup(
            jPanelSeccio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio7.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio7.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel11.setText("7");

        javax.swing.GroupLayout jPanelSeccio7Layout = new javax.swing.GroupLayout(jPanelSeccio7);
        jPanelSeccio7.setLayout(jPanelSeccio7Layout);
        jPanelSeccio7Layout.setHorizontalGroup(
            jPanelSeccio7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelSeccio7Layout.setVerticalGroup(
            jPanelSeccio7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio5.setPreferredSize(new java.awt.Dimension(40, 90));

        jLabel9.setText("5");

        javax.swing.GroupLayout jPanelSeccio5Layout = new javax.swing.GroupLayout(jPanelSeccio5);
        jPanelSeccio5.setLayout(jPanelSeccio5Layout);
        jPanelSeccio5Layout.setHorizontalGroup(
            jPanelSeccio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeccio5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(15, 15, 15))
        );
        jPanelSeccio5Layout.setVerticalGroup(
            jPanelSeccio5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeccio5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(34, 34, 34))
        );

        jPanelSeccio6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio6.setPreferredSize(new java.awt.Dimension(40, 90));

        jLabel10.setText("6");

        javax.swing.GroupLayout jPanelSeccio6Layout = new javax.swing.GroupLayout(jPanelSeccio6);
        jPanelSeccio6.setLayout(jPanelSeccio6Layout);
        jPanelSeccio6Layout.setHorizontalGroup(
            jPanelSeccio6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeccio6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
        );
        jPanelSeccio6Layout.setVerticalGroup(
            jPanelSeccio6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanelSeccio1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio1.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel5.setText("1");

        javax.swing.GroupLayout jPanelSeccio1Layout = new javax.swing.GroupLayout(jPanelSeccio1);
        jPanelSeccio1.setLayout(jPanelSeccio1Layout);
        jPanelSeccio1Layout.setHorizontalGroup(
            jPanelSeccio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelSeccio1Layout.setVerticalGroup(
            jPanelSeccio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio8.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio8.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel12.setText("8");

        javax.swing.GroupLayout jPanelSeccio8Layout = new javax.swing.GroupLayout(jPanelSeccio8);
        jPanelSeccio8.setLayout(jPanelSeccio8Layout);
        jPanelSeccio8Layout.setHorizontalGroup(
            jPanelSeccio8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelSeccio8Layout.setVerticalGroup(
            jPanelSeccio8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanelSeccio3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio3.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel7.setText("3");

        javax.swing.GroupLayout jPanelSeccio3Layout = new javax.swing.GroupLayout(jPanelSeccio3);
        jPanelSeccio3.setLayout(jPanelSeccio3Layout);
        jPanelSeccio3Layout.setHorizontalGroup(
            jPanelSeccio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelSeccio3Layout.setVerticalGroup(
            jPanelSeccio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio10.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio10.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel15.setText("10");

        javax.swing.GroupLayout jPanelSeccio10Layout = new javax.swing.GroupLayout(jPanelSeccio10);
        jPanelSeccio10.setLayout(jPanelSeccio10Layout);
        jPanelSeccio10Layout.setHorizontalGroup(
            jPanelSeccio10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelSeccio10Layout.setVerticalGroup(
            jPanelSeccio10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio13.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio13.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel17.setText("13");

        javax.swing.GroupLayout jPanelSeccio13Layout = new javax.swing.GroupLayout(jPanelSeccio13);
        jPanelSeccio13.setLayout(jPanelSeccio13Layout);
        jPanelSeccio13Layout.setHorizontalGroup(
            jPanelSeccio13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeccio13Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(36, 36, 36))
        );
        jPanelSeccio13Layout.setVerticalGroup(
            jPanelSeccio13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio12.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio12.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel16.setText("12");

        javax.swing.GroupLayout jPanelSeccio12Layout = new javax.swing.GroupLayout(jPanelSeccio12);
        jPanelSeccio12.setLayout(jPanelSeccio12Layout);
        jPanelSeccio12Layout.setHorizontalGroup(
            jPanelSeccio12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel16)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelSeccio12Layout.setVerticalGroup(
            jPanelSeccio12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelSeccio11.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccio11.setPreferredSize(new java.awt.Dimension(90, 40));

        jLabel14.setText("11");

        javax.swing.GroupLayout jPanelSeccio11Layout = new javax.swing.GroupLayout(jPanelSeccio11);
        jPanelSeccio11.setLayout(jPanelSeccio11Layout);
        jPanelSeccio11Layout.setHorizontalGroup(
            jPanelSeccio11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelSeccio11Layout.setVerticalGroup(
            jPanelSeccio11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeccio11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelSeccio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(106, 106, 106)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSeccio6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelSeccio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelSeccio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanelSeccio13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelSeccio10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelSeccio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanelSeccio8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanelSeccio12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanelSeccio11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jPanelSeccio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanelSeccio7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelSeccio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanelSeccio2, jPanelSeccio4, jPanelSeccio7, jPanelSeccio9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanelSeccio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelSeccio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanelSeccio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelSeccio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelSeccio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelSeccio13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelSeccio12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSeccio10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSeccio11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSeccio7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSeccio8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSeccio9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelSeccio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Fruiteria Tres Torres");

        jLabel19.setText("Control d'estock:");

        jTextFieldSliderValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSliderValueActionPerformed(evt);
            }
        });

        jButtonMostraStock.setText("Mostra");

        jLabelTotal.setText("Total:");

        jLabelSliderMin.setText("0");

        jLabelSliderMax.setText("max");

        jTextFieldAfegirCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAfegirCategoriaActionPerformed(evt);
            }
        });

        jButtonFiltaCat.setText("filtra cat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSliderStock, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jTextFieldSliderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButtonMostraStock)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_afegir)
                                        .addComponent(jButtonAfegirCategoria)
                                        .addComponent(jButtonEliminarCategoria))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSliderMin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel19)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelSliderMax))
                                    .addComponent(jComboBoxEliminarCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAfegirCategoria))
                                .addGap(39, 39, 39)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDadaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxBuscarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonInfoBuscarPer)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxOrdenarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBuscarProductes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFiltaCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxBuscarPer, jComboBoxOrdenarPer});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAfegirCategoria, jButtonEliminarCategoria, jButton_afegir, jButton_eliminar, jButton_modificar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_afegir)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAfegirCategoria)
                            .addComponent(jTextFieldAfegirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEliminarCategoria)
                            .addComponent(jComboBoxEliminarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabelSliderMin)
                            .addComponent(jLabelSliderMax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldSliderValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMostraStock)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDadaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxBuscarPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInfoBuscarPer)
                            .addComponent(jComboBoxOrdenarPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarProductes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_eliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTotal)
                        .addComponent(jButtonFiltaCat)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_afegir, jButton_eliminar, jButton_modificar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDadaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDadaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDadaBuscarActionPerformed

    private void jTextFieldSliderValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSliderValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSliderValueActionPerformed

    private void jTextFieldAfegirCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAfegirCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAfegirCategoriaActionPerformed

    private void jButtonEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_tpv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_tpv().setVisible(true);
            }
        });
    }

    public JButton getjButton_afegir() {
        return jButton_afegir;
    }

    public JButton getjButtonFiltaCat() {
        return jButtonFiltaCat;
    }

    public JButton getjButton_eliminar() {
        return jButton_eliminar;
    }

    public JButton getjButtonAfegirCategoria() {
        return jButtonAfegirCategoria;
    }

    public JButton getjButtonEliminarCategoria() {
        return jButtonEliminarCategoria;
    }

    public JComboBox<String> getjComboBoxEliminarCategoria() {
        return jComboBoxEliminarCategoria;
    }

    public JTextField getjTextFieldAfegirCategoria() {
        return jTextFieldAfegirCategoria;
    }

    public JButton getjButton_modificar() {
        return jButton_modificar;
    }

    public JButton getjButtonBuscarProductes() {
        return jButtonBuscarProductes;
    }

    public JButton getjButtonMostraStock() {
        return jButtonMostraStock;
    }

    public JLabel getjLabelTotal() {
        return jLabelTotal;
    }

    public JLabel getjLabelSliderMax() {
        return jLabelSliderMax;
    }

    public JLabel getjLabelSliderMin() {
        return jLabelSliderMin;
    }

    public JSlider getjSliderStock() {
        return jSliderStock;
    }

    public JTextField getjTextFieldSliderValue() {
        return jTextFieldSliderValue;
    }

   
    public JComboBox<String> getjComboBoxBuscarPer() {
        return jComboBoxBuscarPer;
    }

    public JComboBox<String> getjComboBoxOrdenarPer() {
        return jComboBoxOrdenarPer;
    }

    public JTable getjTableMostraDades() {
        return jTableMostraDades;
    }

    public JTextField getjTextFieldDadaBuscar() {
        return jTextFieldDadaBuscar;
    }

    public JButton getjButtonInfoBuscarPer() {
        return jButtonInfoBuscarPer;
    }

    public JPanel getjPanelSeccio1() {
        return jPanelSeccio1;
    }

    public JPanel getjPanelSeccio10() {
        return jPanelSeccio10;
    }

    public JPanel getjPanelSeccio11() {
        return jPanelSeccio11;
    }

    public JPanel getjPanelSeccio12() {
        return jPanelSeccio12;
    }

    public JPanel getjPanelSeccio13() {
        return jPanelSeccio13;
    }

    public JPanel getjPanelSeccio2() {
        return jPanelSeccio2;
    }

    public JPanel getjPanelSeccio3() {
        return jPanelSeccio3;
    }

    public JPanel getjPanelSeccio4() {
        return jPanelSeccio4;
    }

    public JPanel getjPanelSeccio5() {
        return jPanelSeccio5;
    }

    public JPanel getjPanelSeccio6() {
        return jPanelSeccio6;
    }

    public JPanel getjPanelSeccio7() {
        return jPanelSeccio7;
    }

    public JPanel getjPanelSeccio8() {
        return jPanelSeccio8;
    }

    public JPanel getjPanelSeccio9() {
        return jPanelSeccio9;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfegirCategoria;
    private javax.swing.JButton jButtonBuscarProductes;
    private javax.swing.JButton jButtonEliminarCategoria;
    private javax.swing.JButton jButtonFiltaCat;
    private javax.swing.JButton jButtonInfoBuscarPer;
    private javax.swing.JButton jButtonMostraStock;
    private javax.swing.JButton jButton_afegir;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JComboBox<String> jComboBoxBuscarPer;
    private javax.swing.JComboBox<String> jComboBoxEliminarCategoria;
    private javax.swing.JComboBox<String> jComboBoxOrdenarPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSliderMax;
    private javax.swing.JLabel jLabelSliderMin;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanelSeccio1;
    private javax.swing.JPanel jPanelSeccio10;
    private javax.swing.JPanel jPanelSeccio11;
    private javax.swing.JPanel jPanelSeccio12;
    private javax.swing.JPanel jPanelSeccio13;
    private javax.swing.JPanel jPanelSeccio2;
    private javax.swing.JPanel jPanelSeccio3;
    private javax.swing.JPanel jPanelSeccio4;
    private javax.swing.JPanel jPanelSeccio5;
    private javax.swing.JPanel jPanelSeccio6;
    private javax.swing.JPanel jPanelSeccio7;
    private javax.swing.JPanel jPanelSeccio8;
    private javax.swing.JPanel jPanelSeccio9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderStock;
    private javax.swing.JTable jTableMostraDades;
    private javax.swing.JTextField jTextFieldAfegirCategoria;
    private javax.swing.JTextField jTextFieldDadaBuscar;
    private javax.swing.JTextField jTextFieldSliderValue;
    // End of variables declaration//GEN-END:variables
}
